name: energy-tools
summary: Energy Tools for Energy Star and ErP Lot 3
adopt-info: energy-tools
base: core18

grade: devel #stable
confinement: devmode #strict
license: GPL-3.0
architectures: [amd64, i386]

parts:
  energy-tools:
    source: .
    plugin: python
    parse-info: [setup.py]
    stage-packages:
      - dmidecode
      - read-edid
      - python3-debian
      - python3-xlsxwriter

apps:
  energy-tools:
    command: energy-tools
    plugs:
      - hardware-observe
